services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    networks:
      - ms-net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 35s


  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - ms-net

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shop
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app


  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    networks:
      - ms-net

    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shop
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - order-service
    networks:
      - ms-net

networks:
  ms-net: