apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api-gateway=anmolk992/api-gateway
    argocd-image-updater.argoproj.io/api-gateway.update-strategy: name
    argocd-image-updater.argoproj.io/api-gateway.allow-tags: regexp:^main-.*$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/kuanmol/self-hosted-lab.git
    targetRevision: test-image-updater
    path: helm/api-gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true