apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: order-service=anmolk992/order-service
    argocd-image-updater.argoproj.io/order-service.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/kuanmol/self-hosted-lab.git
    targetRevision: test-image-updater
    path: helm/order-service

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true